apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  namespace: ahmed
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
