apiVersion: v1
kind: Service
metadata:
  name: mywebsite-service
  namespace: ahmed
spec:
  selector:
    app: mywebsite
  ports:
  - protocol: TCP
    port: 80           # Port exposed by the Service
    targetPort: 8080   # Port on the container to which the Service routes traffic
  type: LoadBalancer   # Expose the Service using a LoadBalancer
