apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebsite-deployment
  namespace: ahmed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mywebsite
  template:
    metadata:
      labels:
        app: mywebsite
    spec:
      containers:
      - name: mywebsite-container
        image: ahmedkamal18/lms-container:latest
        ports:
        - containerPort: 8080
        
